import {BankProcedureType} from './Types';

export const PAYMENT_METHODS: BankProcedureType[] = [
  {
    bank: 'MANDIRI',
    bank_name: 'MANDIRI',
    list: [
      {
        title: "Livin' by Mandiri",
        list: [
          "Login ke Livin'",
          'Pilih menu "Bayar"',
          'Ketik "DOKU VA Aggregator" atau "88899" pada bagian search',
          'Masukkan No VA "888999013XXXXXXX" secara keseluruhan, lalu masukan nominal, kemudian tekan Lanjutkan',
          'Pastikan detail pembayaran sudah sesuai seperti no VA, Jumlah Pembayaran dan detail lainnya',
          'Pilih Rekening Sumber',
          'Pilih Lanjut Bayar kemudian masukkan PIN dan konfirmasi',
          'Transaksi selesai dan simpan resi sebagai bukti transaksi',
        ],
      },
      {
        title: 'ATM Mandiri',
        list: [
          'Masukkan Kartu ATM Mandiri, lalu pilih Bahasa',
          'Masukkan PIN ATM',
          'Pilih menu "Bayar/Beli"',
          'Pilih menu "Lainnya"',
          'Kemudian tekan kembali "Lainnya"',
          'Pilih menu "Multipayment"',
          'Masukkan Kode Perusahaan / Institusi "88899", kemudian tekan BENAR',
          'Masukkan No VA "888999013XXXXXXX" secara keseluruhan, lalu masukan nominal, kemudian tekan Lanjutkan',
          'Pastikan detail pembayaran sudah sesuai seperti no VA, Jumlah Pembayaran dan detail lainnya',
          'Konfirmasi pembayaran dengan pilih "YA"',
          'Transaksi selesai dan simpan resi sebagai bukti transaksi',
        ],
      },
      {
        title: 'ATM Bank Lain',
        list: [
          'Masukkan PIN',
          'Pilih menu "Transfer"',
          'Pilih "Ke Rek Bank Lain"',
          'Masukkan Kode Bank Mandiri 008 dan kode bayar 88899013XXXXXXX sebagai rekening tujuan, kemudian tekan "Benar"',
          'Masukkan Jumlah pembayaran dan pilih "Benar"',
          'Muncul Layar Konfirmasi Transfer yang berisi Nomor rekening tujuan dan Nama beserta jumlah yang dibayar, jika sudah benar, Tekan "Benar"',
          'Selesai',
        ],
      },
    ],
  },
  {
    bank: 'BSI',
    bank_name: 'BSI',
    list: [
      {
        title: 'BYOND by BSI',
        list: [
          'Masuk dan login BYOND by BSI',
          'Pilih "Bayar & Beli"',
          'Pilih "Virtual Account"',
          'Masukkan nomor 60593010XXXXXXX, dan klik "Lanjutkan"',
          'Periksa informasi yang tertera di layar. Pastikan Merchant adalah DOKU, username dan total tagihan sudah benar. Jika sudah benar, klik "Konfirmasi"',
          'Masukkan PIN dan tunggu transaksi Anda sukses',
          'Transaksi selesai',
        ],
      },
      {
        title: 'BSI Mobile',
        list: [
          'Buka Aplikasi BSI Mobile',
          'Pilih Menu pembayaran',
          'Pilih menu E-commerce',
          'Pilih merchant "DOKU"',
          'Pilih Nomor Rekening',
          'Masukkan No Bayar : 3010XXXXXXX (No Bayar adalah Nomor VA TANPA 4 digit pertama)',
          'Masukkan PIN BSI Mobile',
          'Transaksi selesai',
        ],
      },
      {
        title: 'Banking Syariah Indonesia Net',
        list: [
          'Buka Banking Syariah Indonesia Net',
          'Pilih Menu "pembayaran"',
          'Pilih Jenis Pembayaran "Institusi"',
          'Pilih merchant "DOKU"',
          'Masukkan Nomor Pembayaran : 3010XXXXXXX',
          'Klik tombol "Verifikasi Aplikasi Pembayaran"',
          'Masukkan PIN dan Token Banking Syariah Indonesia Net',
          'Klik tombol "Submit"',
          'Transaksi selesai',
        ],
      },
      {
        title: 'ATM BSI',
        list: [
          'Pilih Bahasa',
          'Masukkan PIN ATM',
          'Pilih "MENU UTAMA"',
          'Pilih menu "PEMBAYARAN/PEMBELIAN"',
          'Pilih menu "AKADEMIK/INSTITUSI"',
          'Masukkan Kode Institusi (6059) dan Nomor Virtual Account (3010XXXXXXX) = 60593010XXXXXXX dan klik "BENAR"',
          'Klik "BENAR" pada slide konfirmasi',
          'Transaksi selesai',
        ],
      },
      {
        title: 'Internet Banking / Mobile Banking lainnya',
        list: [
          'Buka menu Transfer ke Rekening Bank lain',
          'Pilih bank tujuan “Bank Syariah Indonesia (BSI)” dengan kode bank 451',
          'Masukkan Kode Transfer Bank Lain (900), Kode Institusi (6059), dan Kode Pembayaran (3010XXXXXXX) = 60593010XXXXXXX sebagai rekening tujuan, kemudian tekan "Benar"',
          'Masukkan Jumlah Pembayaran. Pastikan Jumlah Pembayaran sesuai dengan invoice. Pembayaran akan gagal jika Jumlah Pembayaran berbeda dengan invoice',
          'Muncul Layar Konfirmasi Transfer yang berisi Nomor rekening tujuan dan Nama beserta jumlah yang dibayar, jika sudah benar',
          'Selesai',
        ],
      },
      {
        title: 'ATM Bank lainnya',
        list: [
          'Buka menu Transfer ke Rekening Bank lain',
          'Masukkan Kode Bank BSI (451), Kode Transfer Bank Lain (900), Kode Institusi (6059), dan Kode Pembayaran (3010XXXXXXX) = 45190060593010XXXXXXX sebagai rekening tujuan, kemudian tekan "Benar"',
          'Masukkan Jumlah Pembayaran dan pilih “Benar”. Pastikan Jumlah Pembayaran sesuai dengan invoice. Pembayaran akan gagal jika Jumlah Pembayaran berbeda dengan invoice',
          'Muncul Layar Konfirmasi Transfer yang berisi Nomor rekening tujuan dan Nama beserta jumlah yang dibayar, jika sudah benar, Tekan "Benar"',
          'Selesai',
        ],
      },
    ],
  },
  {
    bank: 'CIMB Niaga',
    bank_name: 'CIMB',
    list: [
      {
        title: 'Octo Mobile',
        list: [
          'Login ke Octo Mobile',
          'Pilih menu : Transfer',
          'Pilih menu : Transfer to Other CIMB Niaga Account',
          'Pilih Source of fund',
          'Masukkan nomor virtual account 18991020XXXXXXXX',
          'Masukkan jumlah pembayaran (Amount) sesuai tagihan',
          'Klik tombol Next',
          'Nomor virtual account, nama virtual account dan jumlah pembayaran (Amount) ditampilkan pada layar',
          'Klik tombol Confirm',
          'Masukkan Mobile Banking PIN',
        ],
      },
      {
        title: 'Internet Banking Bank Lain',
        list: [
          'Login ke internet banking',
          'Pilih menu transfer ke Bank Lain Online',
          'Pilih bank tujuan Bank CIMB Niaga (kode bank: 022)',
          'Masukkan nomor virtual account 18991020XXXXXXXX',
          'Masukkan jumlah pembayaran sesuai tagihan',
          'Nomor, nama virtual account dan jumlah billing ditampilkan pada layar',
          'Ikuti instruksi untuk menyelesaikan transaksi',
          'Konfirmasi pembayaran ditampilkan pada layar',
        ],
      },
      {
        title: 'OCTO Clicks',
        list: [
          'Login ke OCTO Clicks (https://www.octoclicks.co.id)',
          'Pilih menu : Pembayaran Tagihan',
          'Pilih kategori transaksi : Virtual Account',
          'Pilih rekening sumber dana',
          'Masukkan nomor virtual account 18991020XXXXXXXX dan klik tombol : Lanjutkan untuk verifikasi detail',
          'Nomor virtual account, nama virtual account dan total tagihan ditampilkan pada layar',
          'Masukkan 6 digit OTP dan tekan tombol Submit',
          'Klik tombol Konfirmasi untuk memproses pembayaran',
        ],
      },
      {
        title: 'ATM Alto / Bersama / Prima',
        list: [
          'Masukkan Kartu ATM dan PIN Anda pada mesin ATM bank tersebut',
          'Pilih menu TRANSFER > TRANSFER KE BANK LAIN',
          'Masukkan kode bank CIMB Niaga: 022',
          'Masukkan jumlah pembayaran sesuai tagihan',
          'Masukkan nomor virtual account 18991020XXXXXXXX',
          'Ikuti instruksi untuk menyelesaikan transaksi',
          'Konfirmasi pembayaran ditampilkan pada layar',
        ],
      },
      {
        title: 'ATM CIMB',
        list: [
          'Masukkan Kartu ATM dan PIN CIMB Anda',
          'Pilih menu Pembayaran > Lanjut > Virtual Account',
          'Masukkan nomor virtual account 18991020XXXXXXXX',
          'Pilih rekening debit',
          'Nomor, nama virtual account dan jumlah billing ditampilkan pada layar',
          'Pilih OK untuk melakukan pembayaran',
          'Konfirmasi pembayaran ditampilkan pada layar',
        ],
      },
    ],
  },
  {
    bank: 'BRI',
    bank_name: 'BRI',
    list: [
      {
        title: 'ATM BRI',
        list: [
          'Masukkan Kartu Debit BRI dan PIN Anda',
          'Pilih menu Transaksi Lain > Pembayaran > Lainnya > BRIVA',
          'Masukkan kode pembayaran / virtual account number Anda : 123627012XXXXXXX',
          'Di halaman konfirmasi, pastikan detil pembayaran sudah sesuai seperti Nomor BRIVA, Nama Pelanggan dan Jumlah Pembayaran',
          'Ikuti instruksi untuk menyelesaikan transaksi',
          'Simpan struk transaksi sebagai bukti pembayaran',
        ],
      },
      {
        title: 'Mobile Banking BRI',
        list: [
          'Login aplikasi BRI Mobile',
          'Pilih menu BRIVA',
          'Pilih pembayaran baru',
          'Masukkan kode pembayaran / virtual account number Anda : 123627012XXXXXXX',
          'Di halaman konfirmasi, pastikan detil pembayaran sudah sesuai seperti Nomor BRIVA, Nama Pelanggan dan Total Pembayaran',
          'Masukkan PIN',
          'Simpan notifikasi SMS sebagai bukti pembayaran',
        ],
      },
      {
        title: 'Internet Banking BRI',
        list: [
          'Login pada alamat Internet Banking BRI (https://ib.bri.co.id/ib-bri/Login.html)',
          'Pilih menu Pembayaran Tagihan > Pembayaran > BRIVA',
          'Masukkan kode pembayaran / virtual account number Anda : 123627012XXXXXXX',
          'Di halaman konfirmasi, pastikan detil pembayaran sudah sesuai seperti Nomor BRIVA, Nama Pelanggan dan Jumlah Pembayaran',
          'Masukkan password dan mToken',
          'Cetak/simpan struk pembayaran BRIVA sebagai bukti pembayaran',
        ],
      },
      {
        title: 'Mini ATM/EDC BRI',
        list: [
          'Pilih menu Mini ATM > Pembayaran > BRIVA',
          'Swipe Kartu Debit BRI Anda',
          'Masukkan kode pembayaran / virtual account number Anda : 123627012XXXXXXX',
          'Masukkan PIN',
          'Di halaman konfirmasi, pastikan detil pembayaran sudah sesuai seperti Nomor BRIVA, Nama Pelanggan dan Jumlah Pembayaran',
          'Simpan struk transaksi sebagai bukti pembayaran',
        ],
      },
      {
        title: 'ATM Bank Lain',
        list: [
          'Masukkan Kartu Debit dan PIN Anda',
          'Pilih menu Transaksi Lainnya > Transfer > Ke Rek. Bank Lain',
          'Masukkan kode bank BRI (002), kemudian diikuti dengan nomor virtual account Anda 123627012XXXXXXX',
          'Masukkan nominal pembayaran sesuai dengan jumlah pembayaran pada pesanan anda sesuai yang tertera pada halaman ini',
          'Konfirmasi transaksi dan simpan struk sebagai bukti pembayaran',
        ],
      },
    ],
  },
  {
    bank: 'DANAMON',
    bank_name: 'DANAMON',
    list: [
      {
        title: 'ATM Danamon',
        list: [
          'Masukkan kartu ATM Danamon, lalu masukkan PIN ATM Anda',
          'Pilih menu > "Pembayaran" > "Lainnya" > "Virtual Account"',
          'Masukan 16 digit nomor virtual account (8922600000035990)',
          'Pastikan data pembayaran sudah benar dan pilih "YA"',
          'Transaksi selesai, harap simpan bukti transaksi Anda',
        ],
      },
      {
        title: 'D-Mobile (M-Banking)',
        list: [
          'Akses D-Mobile melalui smartphone Anda',
          'Masukkan User ID dan Password',
          'Pilih menu > "Pembayaran" > "Virtual Account"',
          'Tambahkan biller baru pembayaran',
          'Masukan 16 digit nomor virtual account (8922600000035990)',
          'Pastikan data pembayaran sudah benar',
          'Masukkan mPIN Anda untuk konfirmasi',
          'Transaksi selesai, Anda akan mendapatkan info transaksi',
        ],
      },
      {
        title: 'ATM Bersama/ATM Alto/ATM Prima (Transfer)',
        list: [
          'Masuk ke menu > "Transfer"',
          'Pilih > "Transfer ke bank lain"',
          'Masukkan kode Bank Danamon : 011 + 16 digit nomor virtual account di rekening tujuan (0118922600000035990)',
          'Masukkan jumlah pembayaran sesuai tagihan',
          'Pastikan data pembayaran sudah benar',
          'Pilih > "YA", untuk melanjutkan transaksi',
          'Transaksi selesai, harap simpan bukti transaksi Anda',
        ],
      },
    ],
  },
  {
    bank: 'BTN',
    bank_name: 'BTN',
    list: [
      {
        title: 'Mobile Banking BTN',
        list: [
          'Log-in ke Mobile Banking Bank BTN',
          'Pilih Menu "Pembayaran" lalu pilih menu "Akun Virtual"',
          'Masukan Nomor Virtual Account, klik Lanjut',
          'Informasi pembayaran akan muncul, klik Lanjut',
          'Transaksi Anda selesai. Simpan bukti pembayaran sebagai bukti transaksi',
        ],
      },
      {
        title: 'ATM BTN',
        list: [
          'Masukkan kartu ATM, lalu masukan PIN Anda',
          'Pilih Menu Transaksi Lain',
          'Pilih Menu Pembayaran lalu pilih menu Virtual Account',
          'Masukan Nomor Virtual Account',
          'Tekan Benar jika setuju dengan informasi pembayaran',
          'Lalu tekan Bayar',
          'Transaksi Anda Selesai. Simpan struk ATM untuk bukti transaksi.',
        ],
      },
      {
        title: 'Internet Banking BTN',
        list: [
          'Log-in ke Internet Banking Bank BTN',
          'Pilih Menu Payment',
          'Pilih rekening Anda dan pilih Virtual Account pada bill type',
          'Masukan Nomor Virtual Account, lalu klik Next',
          'Masukan mPasscode lalu klik Submit jika setuju dengan informasi pembayaran',
          'Transaksi Anda selesai. Simpan struk sebagai bukti transaksi',
        ],
      },
    ],
  },
  {
    bank: 'BNI',
    bank_name: 'BNI',
    list: [
      {
        title: 'ATM BNI',
        list: [
          'Buka aplikasi BNI Mobile',
          'Login ke akun BNI Mobile Banking Anda',
          'Pilih "Transfer"',
          'Pilih "Virtual Account Billing", lalu pilih rekening debit Anda',
          'Masukkan Nomor Virtual Account Anda di "Input Baru": 8803300000066900',
          'Konfirmasi bahwa jumlah pembayaran ditampilkan di layar',
          'Masukkan PIN',
          'Konfirmasi transaksi dan masukkan kata sandi transaksi Anda',
          'Transaksi berhasil',
        ],
      },
      {
        title: 'BNI Internet Banking',
        list: [
          'Masukkan kartu ATM BNI, lalu masukkan PIN ATM',
          'Pilih menu "Menu Lain", lalu pilih menu "Transfer"',
          'Pilih Jenis Akun',
          'Pilih "Ke Rekening BNI"',
          'Masukkan nomor rekening dengan Kode Pembayaran (mis.: 7810202001539202) dan pilih "Benar"',
          'Saat Konfirmasi Pembayaran muncul, pilih "Ya"',
          'Transaksi sudah selesai, mohon simpan struknya',
        ],
      },
      {
        title: 'BNI Teller',
        list: [
          'Login Internet Banking, lalu pilih menu "Transfer"',
          'Pilih menu "In-House"',
          'Masukkan nomor rekening dengan Kode Pembayaran Anda (mis.: 7810202001539202) lalu pilih "Kirim"',
          'Masukkan "Kata Sandi" dan OTP Anda',
          'Transaksi sudah selesai, mohon simpan struknya',
        ],
      },
      {
        title: 'Other Bank ATM',
        list: [
          'Kunjungi Teller Bank BNI di Kantor BNI',
          'Isi Formulir Setoran Tunai',
          'Pilih "Tunai" atau tunai. Masukkan Kode Pembayaran (mis.: 781087101123456) dan jumlah. Tulis nama dan tanda tangan Anda',
          'Kirim Formulir Setoran Tunai dan uang tunai ke Teller BNI',
          'Transaksi selesai, mohon simpan salinan Formulir Setoran Tunai sebagai tanda terima pembayaran',
        ],
      },
      {
        title: 'Mobile banking payment',
        list: [
          'Masukkan kartu ATM, lalu masukkan PIN ATM',
          'Pilih menu "Transfer Antar Bank"',
          'Masukkan "Kode Bank Tujuan" : BNI (Kode Bank : 009) + Kode Pembayaran (mis.:781078787101123456)',
          'Masukan "jumlah"',
          'Saat Konfirmasi Transfer muncul, pilih "Ya" / "Lanjut"',
          'Transaksi sudah selesai, silahkan ambil struknya',
        ],
      },
    ],
  },
  {
    bank: 'PERMATA',
    bank_name: 'PERMATA',
    list: [
      {
        title: 'ATM PRIMA/ALTO',
        list: [
          'Masukkan PIN',
          'Pilih "Transfer". Jika menggunakan ATM bank lain, pilih "Pembayaran Lainnya"',
          'Pilih pembayaran lainnya',
          'Masukkan kode bank Permata (013) diikuti 16 digit nomor virtual account anda: 88565019XXXXXXXX kemudian pilih "Benar"',
          'Masukkan nominal yang akan dibayarkan. Pembayaran transaksi gagal akan muncul jika nominal yang dimasukkan salah',
          'Konfirmasi kode bank, nomor virtual account dan nominal pembayaran, jika sudah sesuai pilih "Benar"',
          'Transaksi anda selesai',
        ],
      },
      {
        title: 'Internet Banking Permata (PermataNet)',
        list: [
          'Login ke akun internet banking',
          'Pilih menu “pembayaran” dan pilih "Pembayaran Lainnya. Masukkan kode bank Permata (013) sebagai bank tujuan"',
          'Masukkan nominal transaksi',
          'Masukkan 16 digit nomor virtual account 88565019XXXXXXXX',
          'Konfirmasi kode bank, nomor virtual account dan nominal pembayaran, jika sudah sesuai pilih "Benar"',
          'Selesai',
        ],
      },
      {
        title: 'ATM Permata',
        list: [
          'Masukkan PIN',
          'Pilih menu "Transaksi Lainnya"',
          'Pilih "Pembayaran"',
          'Pilih "Pembayaran Lainnya"',
          'Pilih "Virtual Account"',
          'Masukkan Nomor Virtual Account 88565019XXXXXXXX',
          'Jumlah yang harus dibayar dan nomor rekening akan muncul pada halaman konfirmasi pembayaran. Jika informasi sudah benar pilih "Benar"',
        ],
      },
      {
        title: 'Permata Mobile X',
        list: [
          'Buka aplikasi PermataMobileX',
          'Masukkan User ID & Password',
          'Pilih "Pembayaran Tagihan"',
          'Pilih "Virtual Account"(Akun Virtual)',
          'Masukkan 16 digit Virtual Account yang tertera pada halaman konfirmasi(88565019XXXXXXXX)',
          'Muncul halaman tujuan pembayaran',
          'Masukkan nominal pembayaran sesuai dengan yang ditagihkan',
          'Muncul konfirmasi pembayaran',
          'Masukkan Kode Otentikasi Transaksi',
          'Transaksi selesai',
        ],
      },
    ],
  },
];
